* Added new aircraft command: CMD_IDLEMODE It switch what aircraft will do on idle (Land or dont land) * Fixed bug: Air transport can land if it unloaded not all units * Fixed bug: Not empty air transport lands on stop command
To Auswaschbar:
Your UDPSocket.cpp in not compiling in VS8.
in "throw network_error(std::string(***) + GetErrorMsg());" (4 lines) I receive 52 errors:
..\..\System\Net\UDPSocket.cpp(49) : error C2784: 'std::_String_iterator<_Elem,_Traits,_Alloc> std::operator +(_String_iterator<_Elem,_Traits,_Alloc>::difference_type,std::_String_iterator<_Elem,_Traits,_Alloc>)' : could not deduce template argument for 'std::_String_iterator<_Elem,_Traits,_Alloc>' from 'std::string'
        E:\Program Files\Microsoft Visual Studio 8\VC\include\xstring(438) : see declaration of 'std::operator +'
*****(4 same errors)
..\..\System\Net\UDPSocket.cpp(49) : error C2784: 'std::_String_const_iterator<_Elem,_Traits,_Alloc> std::operator +(_String_const_iterator<_Elem,_Traits,_Alloc>::difference_type,std::_String_const_iterator<_Elem,_Traits,_Alloc>)' : could not deduce template argument for 'std::_String_const_iterator<_Elem,_Traits,_Alloc>' from 'std::string'
        E:\Program Files\Microsoft Visual Studio 8\VC\include\xstring(298) : see declaration of 'std::operator +'
*****(4 same errors)
..\..\System\Net\UDPSocket.cpp(49) : error C2784: 'std::reverse_iterator<_RanIt> std::operator +(_Diff,const std::reverse_iterator<_RanIt> &)' : could not deduce template argument for 'const std::reverse_iterator<_RanIt> &' from 'std::string'
        E:\Program Files\Microsoft Visual Studio 8\VC\include\xutility(1809) : see declaration of 'std::operator +'
*****(4 same errors)
..\..\System\Net\UDPSocket.cpp(49) : error C2676: binary '+' : 'std::basic_string<_Elem,_Traits,_Ax>' does not define this operator or a conversion to a type acceptable to the predefined operator
        with
        [
            _Elem=char,
            _Traits=std::char_traits<char>,
            _Ax=std::allocator<char>
        ]
*****(Same errors for other lines)

git-svn-id: https://spring.clan-sy.com/svn/spring/trunk@4099 37977431-3df6-0310-b722-df95706aa16b