add search path for jvm / java ai's:
fixes/workarounds
java.lang.UnsupportedClassVersionError: ...: Unsupported major.minor version 51.0

when multiple java vms are installed and the newer one is used to compile and older one used to run the ai